version: "3.12"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: fyle:latest
    ports:
      - "7755:7755"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - GUNICORN_PORT=7755
    command: ["gunicorn", "-c", "gunicorn_config.py", "core.server:app"]